Feature/AB#597248 create secrets variable replacer
takenet/blip-sdk-csharp pull request #198
Opened 2024-03-13 13:16 UTC by tuliorezende

In this pull request, we're creating a new variable replacer on SDK to allow bots to use the new `secret` type. This new variable will store values in a Vault mechanism to not allow value exposure on database (like API tokens, credentials and other things).

- Create Variable Replacer
- Adjustments on interface to allow the replacers to know what action is executing
- Unit Tests creation for new variable replacer

Variable usage: `{{secret.?}}`

2024-03-13 13:47 UTC, leonardo-avila approved these changes

2024-04-17 18:23 UTC, Guilhermealvestake requested changes

2024-04-18 18:01 UTC, leonardo-avila commented on src/Take.Blip.Builder/Variables/ResourceVariableProviderBase.cs
> +        protected ResourceVariableProviderBase(ISender sender, IDocumentSerializer documentSerializer, string resourceName, ILogger logger, string commandDestination = "postmaster@msging.net")
Fixed to only add the "To" in Command when the commandDestination not null or empty.

2024-04-22 16:08 UTC, fadoaglauss approved these changes

2024-04-25 14:46 UTC, Guilhermealvestake approved these changes

2024-04-25 15:28 UTC, danteveloso approved these changes

2024-04-25 17:19 UTC, merged