fix SetVariableAsync Script v2
takenet/blip-sdk-csharp pull request #219
Opened 2024-07-23 19:48 UTC by arturpeixot

2024-07-23 21:01 UTC, danteveloso requested changes

2024-07-23 21:01 UTC, danteveloso commented on src/Take.Blip.Builder.UnitTests/Actions/ExecuteScript2ActionTests.cs
> +                CancellationToken);
because that's the natural behavior

2024-07-24 12:58 UTC, Guilhermealvestake approved these changes

2024-07-24 13:11 UTC, danteveloso approved these changes

2024-07-24 13:14 UTC, merged